version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - db_router_DB__uri=postgresql://postgres:postgres@db:5432/db_router
      - db_router_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: db_router_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/db_router_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=db_router, db_router_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
